@startuml
left to right direction
class MoodBuilder {
+ Mood create()
}

enum Mood {
+  SADNESS
+  GLOOM
+  APATHY
+  CALM
}

class Exit {
+ <<Create>> Exit()
+ void execute(String)
}

class Main {
+ {static} void main(String[])
}

class RemoveKey {
- CollectionManager collectionManager
+ <<Create>> RemoveKey(CollectionManager)
+ void execute(String)
}


class CommandManager {
- HashMap<String,Command> commands
+ ArrayDeque<String> lastCommands
+ void addCommand(Command)
+ void execute(String,String)
}


class Insert {
- CollectionManager collectionManager
+ <<Create>> Insert(CollectionManager)
+ void execute(String)
}


class Clear {
- CollectionManager collectionManager
+ <<Create>> Clear(CollectionManager)
+ void execute(String)
}


class Update {
- CollectionManager collectionManager
+ <<Create>> Update(CollectionManager)
+ void execute(String)
}


class Help {
- CollectionManager collectionManager
+ <<Create>> Help(CollectionManager)
+ void execute(String)
}


class CoordinatesBuilder {
+ Coordinates create()
}

class Car {
- String name
+ <<Create>> Car()
+ <<Create>> Car(String)
+ String getName()
+ void setName(String)
+ String toString()
}


class HumanBeingBuilder {
+ HumanBeing create()
+ HumanBeing update(HumanBeing)
}

class CarBuilder {
+ Car create()
}

class EmptyCollectionException {
+ <<Create>> EmptyCollectionException()
}

class RemoveLower {
- CollectionManager collectionManager
+ <<Create>> RemoveLower(CollectionManager)
+ void execute(String)
}


class InvalidDataException {
+ <<Create>> InvalidDataException(String)
}

class Save {
- FileManager fileManager
- String file_path
+ <<Create>> Save(FileManager,String)
+ void execute(String)
}


class CollectionManager {
- TreeMap<Long,HumanBeing> collection
- LocalDate creationDate
+ <<Create>> CollectionManager()
+ TreeMap<Long,HumanBeing> getCollection()
+ void addElement(String,Coordinates,Boolean,Boolean,double,String,int,Mood,Car)
+ void addElement(HumanBeing)
+ void update_ID()
+ void help()
+ void info()
+ void show()
+ void insert(long,HumanBeing)
+ void update(long)
+ void removeKey(long)
+ void clear()
+ void removeLower(HumanBeing)
+ void removeGreaterKey(long)
+ void removeAllByMinutesOfWaiting(int)
+ void printAscending()
+ void printFieldAscendingImpactSpeed()
+ boolean isIDUsed(long)
}


class ScriptExecutorManager {
- {static} ArrayDeque<String> filepaths
- {static} ArrayDeque<Scanner> reader
+ {static} String readfile()
+ {static} void pushFile(String)
+ {static} void popfile()
+ {static} boolean fileReapeting(String)
+ String nextLine()
}


class ExecuteScript {
- CommandManager commandManager
+ <<Create>> ExecuteScript(CommandManager)
+ void execute(String)
}


class FileManager {
- CollectionManager collectionManager
- {static} String SEPARATOR
+ <<Create>> FileManager(CollectionManager)
+ void addFromFile(String)
+ void saveObjects(String)
- String HumanToCsv(HumanBeing)
- Object[] parseHumanFromCsv(String)
}


class FileMod {
+ {static} boolean isFileMod
+ {static} void setFileMod(boolean)
}


class ManualInput {
- {static} Scanner userScanner
+ String nextLine()
}


class Info {
- CollectionManager collectionManager
+ <<Create>> Info(CollectionManager)
+ void execute(String)
}


class HumanBeing {
- long id
- String name
- Coordinates coordinates
- java.util.Date creationDate
- Boolean realHero
- Boolean hasToothpick
- double impactSpeed
- String soundtrackName
- int minutesOfWaiting
- Mood mood
- Car car
- {static} long ID
+ <<Create>> HumanBeing(String,Coordinates,Boolean,Boolean,double,String,int,Mood,Car)
+ {static} void updateID(long)
+ long getId()
+ void setId(long)
+ String getName()
+ void setName(String)
+ Coordinates getCoordinates()
+ void setCoordinates(Coordinates)
+ java.util.Date getCreationDate()
+ void setCreationDate(java.util.Date)
+ Boolean getRealHero()
+ void setRealHero(Boolean)
+ Boolean getHasToothpick()
+ void setHasToothpick(Boolean)
+ double getImpactSpeed()
+ void setImpactSpeed(double)
+ String getSoundtrackName()
+ void setSoundtrackName(String)
+ int getMinutesOfWaiting()
+ void setMinutesOfWaiting(int)
+ Mood getMood()
+ void setMood(Mood)
+ Car getCar()
+ void setCar(Car)
+ int compareTo(HumanBeing)
+ String toString()
+ boolean equals(Object)
+ int hashCode()
}


class Show {
- CollectionManager collectionManager
+ <<Create>> Show(CollectionManager)
+ void execute(String)
}


class UserScanner {
+ {static} Scanner customScanner
+ {static} Scanner getUserScanner()
}


class PrintFieldAscendingImpactSpeed {
- CollectionManager collectionManager
+ <<Create>> PrintFieldAscendingImpactSpeed(CollectionManager)
+ void execute(String)
}


class RemoveGreaterKey {
- CollectionManager collectionManager
+ <<Create>> RemoveGreaterKey(CollectionManager)
+ void execute(String)
}


class Coordinates {
- Double x
- Integer y
+ <<Create>> Coordinates(Double,Integer)
+ Double getX()
+ void setX(Double)
+ Integer getY()
+ void setY(Integer)
+ String getCoordinates()
+ String toString()
}


class History {
- CommandManager commandManager
+ <<Create>> History(CommandManager)
+ void execute(String)
}


abstract class Builder {
# Reader scanner
+ <<Create>> Builder()
+ String buildString(String)
+ Double buildDouble(String)
+ Boolean buildBoolean(String)
+ Long buildLong(String)
+ Integer buildInt(String)
}


interface Reader {
~ String nextLine()
}

class PrintAscending {
- CollectionManager collectionManager
+ <<Create>> PrintAscending(CollectionManager)
+ void execute(String)
}


abstract class Command {
- String name
+ <<Create>> Command(String)
+ String toString()
+ String getName()
+ boolean equals(Object)
+ int hashCode()
+ {abstract}void execute(String)
}


interface Executor {
~ void execute(String)
}

class RemoveAllByMinutesOfWaiting {
- CollectionManager collectionManager
+ <<Create>> RemoveAllByMinutesOfWaiting(CollectionManager)
+ void execute(String)
}




Builder <|-- MoodBuilder
Command <|-- Exit
Command <|-- RemoveKey
Command <|-- Insert
Command <|-- Clear
Command <|-- Update
Command <|-- Help
Builder <|-- CoordinatesBuilder
Builder <|-- HumanBeingBuilder
Builder <|-- CarBuilder
RuntimeException <|-- EmptyCollectionException
Command <|-- RemoveLower
Exception <|-- InvalidDataException
Command <|-- Save
Reader <|.. ScriptExecutorManager
Command <|-- ExecuteScript
Reader <|.. ManualInput
Command <|-- Info
Comparable <|.. HumanBeing
Command <|-- Show
Command <|-- PrintFieldAscendingImpactSpeed
Command <|-- RemoveGreaterKey
Command <|-- History
Command <|-- PrintAscending
Executor <|.. Command
Command <|-- RemoveAllByMinutesOfWaiting
@enduml